CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  login VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  birthday DATE NOT NULL
  );


CREATE TABLE IF NOT EXISTS friendship (
  following_user_id INTEGER,
  followed_user_id INTEGER,
  friendship_status_id INTEGER,
  FOREIGN KEY (following_user_id) REFERENCES users(id),
  FOREIGN KEY (followed_user_id) REFERENCES users(id)
  );

CREATE TABLE IF NOT EXISTS mpa (
  mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
  );

CREATE TABLE IF NOT EXISTS films (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  release_date TIMESTAMP,
  duration INTEGER,
  mpa_id INTEGER,
  FOREIGN KEY (mpa_id) REFERENCES mpa(mpa_id)
  );

CREATE TABLE IF NOT EXISTS genre (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL
  );

CREATE TABLE IF NOT EXISTS film_genre (
  film_id INTEGER,
  genre_id INTEGER,
  FOREIGN KEY (film_id) REFERENCES films(id),
  FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
  );

  CREATE TABLE IF NOT EXISTS film_likes (
      film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
      user_id INTEGER REFERENCES users(id)
  );


